version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: gradle
    directory: "flutter_secure_storage/android"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: gradle
    directory: "flutter_secure_storage/example/android"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/flutter_secure_storage"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/flutter_secure_storage_platform_interface"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/flutter_secure_storage_darwin"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/flutter_secure_storage_linux"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/flutter_secure_storage_web"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pub"
    directory: "/flutter_secure_storage_windows"
    schedule:
      interval: "weekly"
    reviewers:
      - "juliansteenbakker"
    commit-message:
      prefix: "chore"
      include: "scope"
